# Generated by Django 4.2.5 on 2023-11-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='del_flag',
            field=models.BooleanField(default=False),
        ),
    ]
