# Generated by Django 4.2.5 on 2023-11-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_bill_created_at_bill_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='select',
            field=models.BooleanField(default=False),
        ),
    ]
