# Generated by Django 4.2.5 on 2023-11-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_bill_select'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='select',
        ),
        migrations.AddField(
            model_name='product',
            name='select',
            field=models.BooleanField(default=False),
        ),
    ]
