# Generated by Django 4.2.5 on 2023-11-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_bill_select_product_select'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='product_id',
        ),
        migrations.AddField(
            model_name='bill',
            name='product_id',
            field=models.ManyToManyField(to='base.product'),
        ),
    ]
