# Generated by Django 4.2.5 on 2023-11-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_bill_product_id_alter_bill_qty_alter_bill_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='si_no',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='total',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='total_amount',
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('si_no', models.IntegerField(blank=True, null=True)),
                ('qty', models.FloatField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('product_id', models.ManyToManyField(blank=True, null=True, to='base.product')),
            ],
        ),
    ]
