# Generated by Django 4.2.5 on 2023-11-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_bill_product_id_remove_bill_qty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=100)),
                ('digi', models.IntegerField()),
                ('after', models.BigIntegerField()),
            ],
        ),
    ]
