# Generated by Django 4.2.5 on 2023-11-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_billsequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='product_id',
            field=models.ManyToManyField(to='base.product'),
        ),
    ]
