# Generated by Django 4.2.5 on 2023-11-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_billitem_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billitem',
            name='si_no',
        ),
        migrations.AddField(
            model_name='billitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
