# Generated by Django 4.2.5 on 2023-11-16 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_billitem_si_no_billitem_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billitem',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='bill',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billitem',
            name='bill_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.bill'),
        ),
    ]
