# Generated by Django 4.2.5 on 2023-11-16 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_billitem_total_amount_bill_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='product_ids',
            field=models.ManyToManyField(to='base.product'),
        ),
        migrations.RemoveField(
            model_name='billitem',
            name='product_id',
        ),
        migrations.AddField(
            model_name='billitem',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.product'),
        ),
    ]
