# Generated by Django 4.2.5 on 2023-11-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_bill_product_ids_remove_billitem_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
