# Generated by Django 4.2.5 on 2023-11-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_bill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='product_ids',
            field=models.ManyToManyField(blank=True, null=True, to='base.product'),
        ),
    ]
